# Generated by Django 5.0.2 on 2024-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='вопрос')),
                ('options', models.JSONField(verbose_name='Список вариантов')),
                ('answers', models.JSONField(verbose_name='список ответов')),
                ('tipe', models.SmallIntegerField(choices=[(1, 'один вариант'), (2, 'много вариантов'), (3, 'один из многих'), (4, 'много из многих')], default=1, verbose_name='тип карточки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
