# Generated by Django 5.0.2 on 2024-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назание')),
                ('discription', models.TextField(max_length=300, verbose_name='Описание')),
                ('cards', models.ManyToManyField(to='lib.cards', verbose_name='карточки')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотеки',
            },
        ),
    ]
